app = "wst-prt-radio"
primary_region = "iad"

[build]
  dockerfile = "apps/api/Dockerfile"

[env]
  PORT = "3001"
  SQLITE_DB_PATH = "/data/wstprtradio.db"
  STREAM_PUBLIC_URL = "https://radio.wstprtradio.com/radio.mp3"

[mounts]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3001
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1